### ISSUE TITLE
TODO Mini Sprint (Tasks Inside)

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#756]
- [x] Test triage, private, dmp imports on 10.1.141.114 (Rob) 
- [x] Import public studies for Ritika and JJ (Avery)
- [x] Clean up unused DNS entries Route53 (Avery)
- [x] Redump keycloak db and import/rename keycloak service back to main name
- [x] Update the DB references (DNS entires and property files)
- [x] Check in Files 
- [x] Documentation
- [x] CDD/Oncotree stuff

**Comment by averyniceday** [comment]
Documentation Topics

- [x] EKS Pipelines Setup 
- [x] NodeGroups
- [x] KC ConfigMaps
- [x] SSL Certs + Other Ingress Settings
- [x] Versions
- [x] Azure Devops
